version: "3"

services:
    guardian:
        build: ./docker/guardian
        environment:
            - LISTEN_PORT=${LISTEN_PORT:-80}
            - GUARDIAN_URL=${GUARDIAN_URL:-nginx}
            - GUARDIAN_ENV=LIVE
            - APPLICATION_TOKEN=${APPLICATION_TOKEN:-APP_TOKEN_XXXXXXXXXXXX}
        ports:
            - 80:80
            - 443:443

    nginx:
        image: nginx
